### ISSUE TITLE
V-72209: Allow override when another solution is used

### ISSUE THREAD

**Issue by ljkimmel** [mitre/redhat-enterprise-linux-7-stig-baseline#115]
The STIG allows for other logging solutions to be used. Add the ability to disable this control when another logging solution is in use.

**Comment by HackerShark** [comment]
@ljkimmel @aaronlippold @rbclark 

So for this control it doesn't seem like the stig check says anything about disabling or skipping the control if there is other logging solutions used. The exact wording they use is `Note: If another logging package is used, substitute the utility
configuration file for \"/etc/rsyslog.conf\".`

By that wording it just means we just need to query wherever there is a log file no matter what type of logging solution is being used. The way this control is currently written is that the log path is an input so even if you use other logging solution you can point towards that log file and the control will check that the log file is not empty.

If you still need the ability to disable the control for some client specific needs then you would need to create an overlay profile and override the control logic there, but to my knowledge it doesn't seem to fit the case for the baseline.

**Comment by ljkimmel** [comment]
Yes, that is indeed what the STIG says to do. However, it also gives a very specifically formatted configuration to check. Not all "logging packages" will utilize the same format to indicate logging to a remote destination. We can't predict all of the logging solutions that `may` be used and attempt to check for the correct format in each of them.

I think the spirit of the control is to ensure that we have some logging solution in place. In that vein maybe rather than just skipping, we can take an input that allows for a text string describing the implemented solution and then reduce the impact to '0'.

With all that said, looking back at the control code, it isn't sufficient anyhow. It is simply matching what is directed in the STIG, which is to `grep @`. However, the administrator is then expected to ensure that the output from grep matches the more specific text provided. All we're doing is effectively ensuring that there is some uncommented line in the configuration containing the `@` symbol. The rsyslog.conf man page contains an example of a 'template' using the `@` symbols which means it does not uniquely identify the use of remote logging. We need to be much more specific and match `*.* @[@]<text>`. 

Whether or not you agree that we can allow for an adjustment of the impact of the control is understandable either way but this last piece should definitely be fixed.
