### ISSUE TITLE
Cleanup Repository Files

### ISSUE THREAD

**Issue by rbclark** [mitre/redhat-enterprise-linux-7-stig-baseline#121]
There is currently a lot of parts of the repo that are currently completely unused by any of our testing and are currently broken

- `.gemrc` - this is handled differently in CI, and the [docs](https://docs.ruby-lang.org/en/2.1.0/Gem/ConfigFile.html) don't mention the current location as a valid one.
- `.fixtures.yml` - this is required by Beaker, which we are not using for testing
- `Puppetfile` - seems potentially incomplete and currently unused
- `Rakefile` - `bundle exec rake` currently throws an error
- `inputs.nolong.yml.example` - not sure what this one is

And then there's the `spec/` directory
- `spec/fixtures/kitchen/modules/garbage/` - unsure what the purpose of this is
- `spec/fixtures/` - this folder may be completely unused since we aren't using Beaker at all currently
- `spec/puppet/hiera/RedHat/7/` - seems to contain a lot more files than we use, should only contain `global.yaml` and `stig.yaml`. Additionally, the `patches` directory seems unnecessary.

**Comment by em-c-rod** [comment]
These files are no longer present.
