### ISSUE TITLE
V-72037 - Don't change the Description, please let skip_message suffice.

### ISSUE THREAD

**Issue by ejaronne** [mitre/redhat-enterprise-linux-7-stig-baseline#164]
For https://github.com/mitre/redhat-enterprise-linux-7-stig-baseline/blob/master/controls/V-72037.rb , do not change the description based on the input "disable_slow_controls". This creates confusion because the user has no idea what the context of the actual control would be if they choose to set disable_slow_controls to false. Besides, the skip_message is more than sufficient to state why the control was disabled:

https://github.com/mitre/redhat-enterprise-linux-7-stig-baseline/blob/4d1347c86a58008069f15a92ab797ad192198fb3/controls/V-72037.rb#L5-L14 

Instead, leave the description as the original description from the requirement, please!

**Comment by em-c-rod** [comment]
This has been resolved. The new ID number for this control is SV-204478.
