### ISSUE TITLE
V-71939 - False fails due to not checking all passing configurations

### ISSUE THREAD

**Issue by ejaronne** [mitre/redhat-enterprise-linux-7-stig-baseline#165]
In https://github.com/mitre/redhat-enterprise-linux-7-stig-baseline/blob/master/controls/V-71939.rb, the STIG Author defines these 3 configurations as passing:

"If no line, a commented line, or a line indicating the value \"no\" is returned, the required value is set."
https://github.com/mitre/redhat-enterprise-linux-7-stig-baseline/blob/4d1347c86a58008069f15a92ab797ad192198fb3/controls/V-71939.rb#L16-L17

However, the describe block only checks for "PermitEmptyPasswords no", which is only one of the 3 configurations allowed to pass. The other two: no line, or a commented line, should be checked to alternatively allow a pass.

**Comment by em-c-rod** [comment]
Updated control number: SV-204425
