### ISSUE TITLE
SV-204458 Profile Error for releases not covered

### ISSUE THREAD

**Issue by karikarshivani** [mitre/redhat-enterprise-linux-7-stig-baseline#188]
My target release is `7.3` which doesn't have a value assigned in the case statement. To avoid the following profile error:
![Screen Shot 2023-04-14 at 3 22 42 PM](https://user-images.githubusercontent.com/11844975/232137314-9a05da1c-4cf9-467c-9065-0e754e640612.png)

We can maybe try:
```rb
release = os.release

if !['7.6', '7.7', '7.9'].include? release
# fail
  describe "RHEL \"#{release}\" is not a supported release" do
    subject { EOMS_DATE }
    it { should_not be_nil }
    end
else
EOMS_DATE = case release
              when /^7\.6/
                '31 May 2021'
              when /^7\.7/
                '30 August 2021'
              when /^7\.9/
                '30 June 2024'
              end

  describe "The release \"#{release}\" must still be within the support window, ending #{EOMS_DATE}" do
    subject { Date.today <= Date.parse(EOMS_DATE) }
    it { should be true }
  end
end
```

**Comment by em-c-rod** [comment]
Can reference the Red Hat documentation https://access.redhat.com/product-life-cycles?product=Red%20Hat%20Enterprise%20Linux,OpenShift%20Container%20Platform%204
