### ISSUE TITLE
Inputs with no default value

### ISSUE THREAD

**Issue by ljkimmel** [mitre/redhat-enterprise-linux-7-stig-baseline#19]
firewalld_services_deny
firewalld_zones
firewalld_services
firewalld_hosts_allow
firewalld_hosts_deny
firewalld_ports_allow
firewalld_ports_deny
tcpwrappers_allow
tcpwrappers_deny
iptables_rules
max_retry
skip_deprecated_test (This one should just be removed from all controls)

**Comment by ljkimmel** [comment]
This looks like a side effect from generating the latest STIG metadata but not including default input values at the top of some control files.
Do we want to incorporate that code or just put defaults into Inspec.yml?

**Comment by aaronlippold** [comment]
Defaults should go in the inspec.yml
