### ISSUE TITLE
testing workflows should trigger off of all PRs not just those against main

### ISSUE THREAD

**Issue by Amndeep7** [mitre/redhat-enterprise-linux-7-stig-baseline#202]
https://github.com/mitre/redhat-enterprise-linux-7-stig-baseline/blob/main/.github/workflows/verify-ec2.yml#L7

^ this line and the same for the vagrant one = BAD

**Comment by em-c-rod** [comment]
https://github.com/mitre/redhat-enterprise-linux-7-stig-baseline/commit/8dc5f9621686e1d928fe894ea9f109a7568f1e79
