### ISSUE TITLE
ARS 5 tasks

### ISSUE THREAD

**Issue by karikarshivani** [mitre/redhat-enterprise-linux-7-stig-baseline#210]
- [x] **SV-204407:** Create an issue for RHEL 8 baseline+overlay to create an input+update value in overlay
- [x] **SV-204408:** Add to the previous issue for RHEL 8 baseline+overlay to create an input+update value in overlay
- [x] **SV-204409:** Add to the previous issue for RHEL 8 baseline+overlay to create an input+update value in overlay
- [x] **SV-204422:** Parameterize using `min_reuse_generations`, update value in overlay (details in tracker)
- [x] **SV-204426:** `max_days_of_inactivity` not an input anymore. Use `days_of_inactivity` instead.
- [x] **SV-204427:** `expected_<name>` inputs don't exist anymore. Use the appropriate inputs instead to parameterize.
- [x] **SV-204428:** `expected_<name>` inputs don't exist anymore. Use the appropriate inputs instead to parameterize.
- [x] **Baseline:** Search for inputs used in the controls directory to see if any of them are outdated/don't exist in the `inspec.yml`.
- [x] **Overlay inspec.yml:** Ensure that explicit conditions are used instead of `else` as a catch-all
- [x] **Baseline inspec.yml:** Remove the redundant `lockout_time` with the value of 604800 after confirming with Eugene
- [x] **SV-204409:** Create an input, parameterize, override values in overlay (details in tracker). Add this control to HVA NA lists.
- [x] **SV-204410:** Set as NA for all system categorizations (details in tracker). 
- [x] **SV-204427:** Update values of inputs in the overlay after they are paramterized in the baseline (details in tracker).
- [x] **SV-204428:** Update values of inputs in the overlay after they are paramterized in the baseline (details in tracker).
- [x] **overlay.rb:** Semantic changes for **SV-204577** based on PPSM examples from [MySQL](https://github.com/CMS-Enterprise/cms-ars-5.0-oracle-mysql-8-stig-overlay/blob/main/controls/overlay.rb#L23:L49) and [K8S Cluster](https://github.com/CMS-Enterprise/cms-ars-5.0-k8s-cluster-stig-overlay/blob/main/controls/overlay.rb)
- [x] **Baseline controls:** Define the key for `org_name`
- [x] **SV-204587:** Remove `max_` from input name to match existing input
- [x] **SV-254523:** Declare the input `emergency_account_disable` in inspec.yml
- [x] **SV-255926:** Parameterize `15` using `system_activity_timeout`

**Comment by ssayed118** [comment]
SV-204422: [baseline commit](https://github.com/mitre/redhat-enterprise-linux-7-stig-baseline/commit/50fbd364155cf45c30e4340ec126fff57e4e1fd1) & [overlay commit](https://github.com/mitre/working-cms-ars-5.0-red-hat-enterprise-linux-7-stig-overlay/commit/acf81f1dbd125ccf79e399a748d559b8ee491c78)

**Comment by ejaronne** [comment]
For SV-204577, in the overlay.rb for CMS ARS 5, add the following semantic update:

```
control 'SV-204577' do
  title 'The Red Hat Enterprise Linux operating system must be configured to prohibit or restrict the use of
    functions, ports, protocols, and/or services.'
   desc 'check', 'Inspect the firewall configuration and running services to verify that it is configured to prohibit
    or restrict the use of functions, ports, protocols, and/or services that are unnecessary or prohibited.
    Check which services are currently active with the following command:
    # firewall-cmd --list-all
    public (default, active)
    interfaces: enp0s3
    sources:
    services: dhcpv6-client dns http https ldaps rpc-bind ssh
    ports:
    masquerade: no
    forward-ports:
    icmp-blocks:
    rich rules:
    Verify the services allowed by the firewall match what is permitted by CMS.
    If there are additional ports, protocols, or services that are not permitted, or there are ports, protocols,
    or services that are prohibited by CMS, this is a finding.'
  desc 'fix', "Update the host's firewall settings and/or running services to comply with the CMS requirements."
end
```

**Comment by karikarshivani** [comment]
[PR merged](https://github.com/mitre/redhat-enterprise-linux-7-stig-baseline/pull/203)
