### ISSUE TITLE
V-72219: No implicit conversion of String into Integer

### ISSUE THREAD

**Issue by ljkimmel** [mitre/redhat-enterprise-linux-7-stig-baseline#28]
Control throwing this error.

**Comment by ljkimmel** [comment]
@aaronlippold -- What are your thoughts on the current implementation of this control? The code seems to enforce that we provide a list of ‘denied’ services and ports for firewalld. It validates that the services or ports in those lists are not allowed by the current firewalld configuration. This doesn’t make sense to me since the firewall is typically a whitelist, not a blacklist. All one would have to do is list a single, random service to pass the checks.
More realistically, I think the input should be a list of services and ports that we expect to be open and validate that no others outside of that list are enabled.

**Comment by aaronlippold** [comment]
@HackerShark  and @djhaynes  and trevor  worked our a plan on this one I think. This is one of the more complicated ones so I think a actual talk is needed.

**Comment by aaronlippold** [comment]
I think perhaps using profile files may work out better here. Much like the services example in the Docs

**Comment by ljkimmel** [comment]
Digging into this, I think that it may have been constructed this way due to shortcomings in the firewalld resource. Specifically, the inability to validate ports configured for a zone. I am currently looking into creating and Inspec PR to add that feature.

**Comment by ljkimmel** [comment]
The error is coming from the fact that, in inspec.yml. `firewalld_ports_deny` is defined as an Array but should be a Hash mapping a zone name to an array of ports. 
Also, the string 'public' on line 92 should be changed to variable 'zone'.
Finally, it appears that Ruby ingests Hash values and casts the key names to symbols. When we attempt reference the variable `zone` as a hash key nothing is returned because `zone` is a string but the hash keys are symbols. The `zone` variable needs to be cast to a symbol (zone.to_sym) on both lines 92 & 93.
