### ISSUE TITLE
V-72001: Use only 'restricted' accounts?

### ISSUE THREAD

**Issue by ljkimmel** [mitre/redhat-enterprise-linux-7-stig-baseline#39]
This control currently requires you to configure 'known_system_accounts' as well as 'disallowed_accounts'. Valid interactive users must be configured as 'user_accounts'. This creates a huge management overhead as well as making it mandatory to maintain profiles for various systems or system types. Installation of various software packages can add valid system accounts but then these accounts need to be added back to the 'known_system_accounts' list. 

Simply listing 'disallowed_accounts' should be sufficient.
@aaronlippold ?
@HackerShark ?

**Comment by ljkimmel** [comment]
@aaronlippold @trevor-vaughan 
I've decided that it makes sense for reporting to validate against a list of valid users. However, I'm still struggling with the concept of 'disallowed_accounts'. By virtue of not being `allowed` an account is already `disallowed`.
The only use case I can think of is if you want to selectively disable a known_system_account without having to redefine the entire known_system_accounts array in an overlay.

**Comment by trevor-vaughan** [comment]
@ljkimmel Honestly, this control is just written for a no-win.

Enumerating all allowed accounts is pretty much impossible and personally, I think, kind of silly.

If we're going to go this way, only standard system accounts on a minimal system should be present and the additions that are in the current list should be removed.

Enumerating disallowed accounts makes complete sense.

**Comment by ljkimmel** [comment]
@trevor-vaughan Can you elaborate on how disallowed accounts makes sense? This control only considers users present in /etc/passwd, not any coming from external auth sources. Therefore, the list of allowed/expected accounts should remain [relatively] small. In this day of immutable and commodity systems it's easy enough to know what small number of local accounts are expected based on the application deployed.  
Again, if an account is not 'allowed' it is inherently 'disallowed'. What accounts get added to the 'disallowed' list? It could grow infinitely. The control states to validate whether accounts `present` on the system are authorized. This authorization is implied by someone explicitly adding them to a list of allowed users. It doesn't ask to report users that are `not present`. While it give examples of 'games' and 'gopher' we could list random accounts that we don't want present all day. Shouldn't we rather just list the local users from passwd and confirm that we expected to see them?

**Comment by trevor-vaughan** [comment]
Personally, I'm OK with enumerating the base list and calling the disallowed accounts done.

It'll have to stop at the system UID_MIN though.

**Comment by ljkimmel** [comment]
My last comment may have come off bluntly. I'm not necessarily arguing one way or the other. I am expressing my understanding and thoughts at the moment. I am open and interested in understanding other points of view. I don't want to fundamentally change this control if it was designed this way for a purpose. I would just like to understand that purpose because I currently don't.

**Comment by trevor-vaughan** [comment]
@ljkimmel Nah, you were fine. I don't get the point either except for groups that want to say "THESE" groups are not allowed (which, I guess, means that all of the other ones are)
