### ISSUE TITLE
Modify controls to place impact adjustment with main code body

### ISSUE THREAD

**Issue by ljkimmel** [mitre/redhat-enterprise-linux-7-stig-baseline#69]
Having an if/then control structure buried amongst other data makes it easy to miss. We are standardizing on updating the impact where decisions are made regarding tests to be run in the main code body.

The following controls need to be considered:
V-71955.rb
V-71995.rb
V-72081.rb
V-72135.rb
V-72137.rb
V-72139.rb
V-72141.rb
V-72145.rb
V-72147.rb
V-72149.rb
V-72151.rb
V-72153.rb
V-72155.rb
V-72157.rb
V-72159.rb
V-72161.rb
V-72163.rb
V-72165.rb
V-72167.rb
V-72173.rb
V-72175.rb
V-72177.rb
V-72179.rb
V-72183.rb
V-72185.rb
V-72191.rb
V-72197.rb
V-72305.rb
V-72313.rb
V-72317.rb
V-72427.rb
V-73155.rb
V-73157.rb
V-73165.rb
V-73167.rb
V-73171.rb
V-73173.rb
V-77819.rb
V-78997.rb

**Comment by HackerShark** [comment]
PR #82 fixes this

**Comment by ljkimmel** [comment]
I was wondering if we wanted to leave the 'default' impact in the 'metadata' area and then put any overrides in the main body. Thoughts?

**Comment by HackerShark** [comment]
Closing as PR has been merged
